### ISSUE TITLE
Add all past and present DR students info on site

### ISSUE THREAD

**Issue by thammegowda** [USCDataScience/uscdatascience.github.io#10]

**Comment by chrismattmann** [comment]
@thammegowda the top level header thinks we are in the Projects section when we are browsing DR students. Can you fix?

**Comment by thammegowda** [comment]
@chrismattmann That was a small glitch due to dynamic modification of page. Fixed in ffeeb18d408ebf6c8c359f04736260a12adb5271 . The fix is merged to master and deployed.. please test.

**Comment by chrismattmann** [comment]
thanks @thammegowda

**Comment by smadha** [comment]
Reopen if some work is left on this issue
